/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminCriteriaRouteImport } from './routes/admin.criteria'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as MainHomeRouteImport } from './routes/_main.home'
import { Route as MainCalendarRouteImport } from './routes/_main.calendar'
import { Route as MainBoardIndexRouteImport } from './routes/_main.board.index'
import { Route as MainBoardSlugRouteImport } from './routes/_main.board.$slug'
import { Route as MainBoardSlugIndexRouteImport } from './routes/_main.board.$slug.index'
import { Route as MainBoardSlugNewQuestionRouteImport } from './routes/_main.board.$slug.new-question'
import { Route as MainBoardSlugNewProjectRouteImport } from './routes/_main.board.$slug.new-project'
import { Route as MainBoardSlugNewGeneralRouteImport } from './routes/_main.board.$slug.new-general'
import { Route as MainBoardSlugPostNoRouteImport } from './routes/_main.board.$slug.$postNo'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCriteriaRoute = AdminCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainCalendarRoute = MainCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MainRoute,
} as any)
const MainBoardIndexRoute = MainBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => MainRoute,
} as any)
const MainBoardSlugRoute = MainBoardSlugRouteImport.update({
  id: '/board/$slug',
  path: '/board/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainBoardSlugIndexRoute = MainBoardSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewQuestionRoute =
  MainBoardSlugNewQuestionRouteImport.update({
    id: '/new-question',
    path: '/new-question',
    getParentRoute: () => MainBoardSlugRoute,
  } as any)
const MainBoardSlugNewProjectRoute = MainBoardSlugNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewGeneralRoute = MainBoardSlugNewGeneralRouteImport.update({
  id: '/new-general',
  path: '/new-general',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugPostNoRoute = MainBoardSlugPostNoRouteImport.update({
  id: '/$postNo',
  path: '/$postNo',
  getParentRoute: () => MainBoardSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof MainCalendarRoute
  '/home': typeof MainHomeRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/board/$slug': typeof MainBoardSlugRouteWithChildren
  '/board/': typeof MainBoardIndexRoute
  '/board/$slug/$postNo': typeof MainBoardSlugPostNoRoute
  '/board/$slug/new-general': typeof MainBoardSlugNewGeneralRoute
  '/board/$slug/new-project': typeof MainBoardSlugNewProjectRoute
  '/board/$slug/new-question': typeof MainBoardSlugNewQuestionRoute
  '/board/$slug/': typeof MainBoardSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof MainCalendarRoute
  '/home': typeof MainHomeRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/board': typeof MainBoardIndexRoute
  '/board/$slug/$postNo': typeof MainBoardSlugPostNoRoute
  '/board/$slug/new-general': typeof MainBoardSlugNewGeneralRoute
  '/board/$slug/new-project': typeof MainBoardSlugNewProjectRoute
  '/board/$slug/new-question': typeof MainBoardSlugNewQuestionRoute
  '/board/$slug': typeof MainBoardSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_main/calendar': typeof MainCalendarRoute
  '/_main/home': typeof MainHomeRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/_main/board/$slug': typeof MainBoardSlugRouteWithChildren
  '/_main/board/': typeof MainBoardIndexRoute
  '/_main/board/$slug/$postNo': typeof MainBoardSlugPostNoRoute
  '/_main/board/$slug/new-general': typeof MainBoardSlugNewGeneralRoute
  '/_main/board/$slug/new-project': typeof MainBoardSlugNewProjectRoute
  '/_main/board/$slug/new-question': typeof MainBoardSlugNewQuestionRoute
  '/_main/board/$slug/': typeof MainBoardSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/home'
    | '/admin/calendar'
    | '/admin/categories'
    | '/admin/criteria'
    | '/admin/notices'
    | '/admin/settings'
    | '/admin/'
    | '/board/$slug'
    | '/board/'
    | '/board/$slug/$postNo'
    | '/board/$slug/new-general'
    | '/board/$slug/new-project'
    | '/board/$slug/new-question'
    | '/board/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/home'
    | '/admin/calendar'
    | '/admin/categories'
    | '/admin/criteria'
    | '/admin/notices'
    | '/admin/settings'
    | '/admin'
    | '/board'
    | '/board/$slug/$postNo'
    | '/board/$slug/new-general'
    | '/board/$slug/new-project'
    | '/board/$slug/new-question'
    | '/board/$slug'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/admin'
    | '/_main/calendar'
    | '/_main/home'
    | '/admin/calendar'
    | '/admin/categories'
    | '/admin/criteria'
    | '/admin/notices'
    | '/admin/settings'
    | '/admin/'
    | '/_main/board/$slug'
    | '/_main/board/'
    | '/_main/board/$slug/$postNo'
    | '/_main/board/$slug/new-general'
    | '/_main/board/$slug/new-project'
    | '/_main/board/$slug/new-question'
    | '/_main/board/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/criteria': {
      id: '/admin/criteria'
      path: '/criteria'
      fullPath: '/admin/criteria'
      preLoaderRoute: typeof AdminCriteriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/calendar': {
      id: '/_main/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof MainCalendarRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/board/': {
      id: '/_main/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof MainBoardIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/board/$slug': {
      id: '/_main/board/$slug'
      path: '/board/$slug'
      fullPath: '/board/$slug'
      preLoaderRoute: typeof MainBoardSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/board/$slug/': {
      id: '/_main/board/$slug/'
      path: '/'
      fullPath: '/board/$slug/'
      preLoaderRoute: typeof MainBoardSlugIndexRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-question': {
      id: '/_main/board/$slug/new-question'
      path: '/new-question'
      fullPath: '/board/$slug/new-question'
      preLoaderRoute: typeof MainBoardSlugNewQuestionRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-project': {
      id: '/_main/board/$slug/new-project'
      path: '/new-project'
      fullPath: '/board/$slug/new-project'
      preLoaderRoute: typeof MainBoardSlugNewProjectRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-general': {
      id: '/_main/board/$slug/new-general'
      path: '/new-general'
      fullPath: '/board/$slug/new-general'
      preLoaderRoute: typeof MainBoardSlugNewGeneralRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/$postNo': {
      id: '/_main/board/$slug/$postNo'
      path: '/$postNo'
      fullPath: '/board/$slug/$postNo'
      preLoaderRoute: typeof MainBoardSlugPostNoRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
  }
}

interface MainBoardSlugRouteChildren {
  MainBoardSlugPostNoRoute: typeof MainBoardSlugPostNoRoute
  MainBoardSlugNewGeneralRoute: typeof MainBoardSlugNewGeneralRoute
  MainBoardSlugNewProjectRoute: typeof MainBoardSlugNewProjectRoute
  MainBoardSlugNewQuestionRoute: typeof MainBoardSlugNewQuestionRoute
  MainBoardSlugIndexRoute: typeof MainBoardSlugIndexRoute
}

const MainBoardSlugRouteChildren: MainBoardSlugRouteChildren = {
  MainBoardSlugPostNoRoute: MainBoardSlugPostNoRoute,
  MainBoardSlugNewGeneralRoute: MainBoardSlugNewGeneralRoute,
  MainBoardSlugNewProjectRoute: MainBoardSlugNewProjectRoute,
  MainBoardSlugNewQuestionRoute: MainBoardSlugNewQuestionRoute,
  MainBoardSlugIndexRoute: MainBoardSlugIndexRoute,
}

const MainBoardSlugRouteWithChildren = MainBoardSlugRoute._addFileChildren(
  MainBoardSlugRouteChildren,
)

interface MainRouteChildren {
  MainCalendarRoute: typeof MainCalendarRoute
  MainHomeRoute: typeof MainHomeRoute
  MainBoardSlugRoute: typeof MainBoardSlugRouteWithChildren
  MainBoardIndexRoute: typeof MainBoardIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCalendarRoute: MainCalendarRoute,
  MainHomeRoute: MainHomeRoute,
  MainBoardSlugRoute: MainBoardSlugRouteWithChildren,
  MainBoardIndexRoute: MainBoardIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCriteriaRoute: typeof AdminCriteriaRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCriteriaRoute: AdminCriteriaRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
