/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminProfilesRouteImport } from './routes/admin.profiles'
import { Route as AdminProblemOptionsRouteImport } from './routes/admin.problem-options'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminCriteriaRouteImport } from './routes/admin.criteria'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as MainSearchRouteImport } from './routes/_main.search'
import { Route as MainReadmeRouteImport } from './routes/_main.readme'
import { Route as MainMypageRouteImport } from './routes/_main.mypage'
import { Route as MainHomeRouteImport } from './routes/_main.home'
import { Route as MainGuideRouteImport } from './routes/_main.guide'
import { Route as MainCalendarRouteImport } from './routes/_main.calendar'
import { Route as MainBoardIndexRouteImport } from './routes/_main.board.index'
import { Route as MainBoardSlugRouteImport } from './routes/_main.board.$slug'
import { Route as MainBoardSlugIndexRouteImport } from './routes/_main.board.$slug.index'
import { Route as MainBoardSlugNewVoteRouteImport } from './routes/_main.board.$slug.new-vote'
import { Route as MainBoardSlugNewRecordRouteImport } from './routes/_main.board.$slug.new-record'
import { Route as MainBoardSlugNewQuestionRouteImport } from './routes/_main.board.$slug.new-question'
import { Route as MainBoardSlugNewProjectRouteImport } from './routes/_main.board.$slug.new-project'
import { Route as MainBoardSlugNewProblemRouteImport } from './routes/_main.board.$slug.new-problem'
import { Route as MainBoardSlugNewLinkRouteImport } from './routes/_main.board.$slug.new-link'
import { Route as MainBoardSlugNewGeneralRouteImport } from './routes/_main.board.$slug.new-general'
import { Route as MainBoardSlugPostNoRouteImport } from './routes/_main.board.$slug.$postNo'
import { Route as MainBoardSlugSeriesSeriesRouteImport } from './routes/_main.board.$slug.series.$series'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemOptionsRoute = AdminProblemOptionsRouteImport.update({
  id: '/problem-options',
  path: '/problem-options',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCriteriaRoute = AdminCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainReadmeRoute = MainReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => MainRoute,
} as any)
const MainMypageRoute = MainMypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => MainRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainGuideRoute = MainGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => MainRoute,
} as any)
const MainCalendarRoute = MainCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MainRoute,
} as any)
const MainBoardIndexRoute = MainBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => MainRoute,
} as any)
const MainBoardSlugRoute = MainBoardSlugRouteImport.update({
  id: '/board/$slug',
  path: '/board/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainBoardSlugIndexRoute = MainBoardSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewVoteRoute = MainBoardSlugNewVoteRouteImport.update({
  id: '/new-vote',
  path: '/new-vote',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewRecordRoute = MainBoardSlugNewRecordRouteImport.update({
  id: '/new-record',
  path: '/new-record',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewQuestionRoute =
  MainBoardSlugNewQuestionRouteImport.update({
    id: '/new-question',
    path: '/new-question',
    getParentRoute: () => MainBoardSlugRoute,
  } as any)
const MainBoardSlugNewProjectRoute = MainBoardSlugNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewProblemRoute = MainBoardSlugNewProblemRouteImport.update({
  id: '/new-problem',
  path: '/new-problem',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewLinkRoute = MainBoardSlugNewLinkRouteImport.update({
  id: '/new-link',
  path: '/new-link',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugNewGeneralRoute = MainBoardSlugNewGeneralRouteImport.update({
  id: '/new-general',
  path: '/new-general',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugPostNoRoute = MainBoardSlugPostNoRouteImport.update({
  id: '/$postNo',
  path: '/$postNo',
  getParentRoute: () => MainBoardSlugRoute,
} as any)
const MainBoardSlugSeriesSeriesRoute =
  MainBoardSlugSeriesSeriesRouteImport.update({
    id: '/series/$series',
    path: '/series/$series',
    getParentRoute: () => MainBoardSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof MainCalendarRoute
  '/guide': typeof MainGuideRoute
  '/home': typeof MainHomeRoute
  '/mypage': typeof MainMypageRoute
  '/readme': typeof MainReadmeRoute
  '/search': typeof MainSearchRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/problem-options': typeof AdminProblemOptionsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/board/$slug': typeof MainBoardSlugRouteWithChildren
  '/board/': typeof MainBoardIndexRoute
  '/board/$slug/$postNo': typeof MainBoardSlugPostNoRoute
  '/board/$slug/new-general': typeof MainBoardSlugNewGeneralRoute
  '/board/$slug/new-link': typeof MainBoardSlugNewLinkRoute
  '/board/$slug/new-problem': typeof MainBoardSlugNewProblemRoute
  '/board/$slug/new-project': typeof MainBoardSlugNewProjectRoute
  '/board/$slug/new-question': typeof MainBoardSlugNewQuestionRoute
  '/board/$slug/new-record': typeof MainBoardSlugNewRecordRoute
  '/board/$slug/new-vote': typeof MainBoardSlugNewVoteRoute
  '/board/$slug/': typeof MainBoardSlugIndexRoute
  '/board/$slug/series/$series': typeof MainBoardSlugSeriesSeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof MainCalendarRoute
  '/guide': typeof MainGuideRoute
  '/home': typeof MainHomeRoute
  '/mypage': typeof MainMypageRoute
  '/readme': typeof MainReadmeRoute
  '/search': typeof MainSearchRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/problem-options': typeof AdminProblemOptionsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/board': typeof MainBoardIndexRoute
  '/board/$slug/$postNo': typeof MainBoardSlugPostNoRoute
  '/board/$slug/new-general': typeof MainBoardSlugNewGeneralRoute
  '/board/$slug/new-link': typeof MainBoardSlugNewLinkRoute
  '/board/$slug/new-problem': typeof MainBoardSlugNewProblemRoute
  '/board/$slug/new-project': typeof MainBoardSlugNewProjectRoute
  '/board/$slug/new-question': typeof MainBoardSlugNewQuestionRoute
  '/board/$slug/new-record': typeof MainBoardSlugNewRecordRoute
  '/board/$slug/new-vote': typeof MainBoardSlugNewVoteRoute
  '/board/$slug': typeof MainBoardSlugIndexRoute
  '/board/$slug/series/$series': typeof MainBoardSlugSeriesSeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_main/calendar': typeof MainCalendarRoute
  '/_main/guide': typeof MainGuideRoute
  '/_main/home': typeof MainHomeRoute
  '/_main/mypage': typeof MainMypageRoute
  '/_main/readme': typeof MainReadmeRoute
  '/_main/search': typeof MainSearchRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/problem-options': typeof AdminProblemOptionsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/_main/board/$slug': typeof MainBoardSlugRouteWithChildren
  '/_main/board/': typeof MainBoardIndexRoute
  '/_main/board/$slug/$postNo': typeof MainBoardSlugPostNoRoute
  '/_main/board/$slug/new-general': typeof MainBoardSlugNewGeneralRoute
  '/_main/board/$slug/new-link': typeof MainBoardSlugNewLinkRoute
  '/_main/board/$slug/new-problem': typeof MainBoardSlugNewProblemRoute
  '/_main/board/$slug/new-project': typeof MainBoardSlugNewProjectRoute
  '/_main/board/$slug/new-question': typeof MainBoardSlugNewQuestionRoute
  '/_main/board/$slug/new-record': typeof MainBoardSlugNewRecordRoute
  '/_main/board/$slug/new-vote': typeof MainBoardSlugNewVoteRoute
  '/_main/board/$slug/': typeof MainBoardSlugIndexRoute
  '/_main/board/$slug/series/$series': typeof MainBoardSlugSeriesSeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/guide'
    | '/home'
    | '/mypage'
    | '/readme'
    | '/search'
    | '/admin/calendar'
    | '/admin/categories'
    | '/admin/criteria'
    | '/admin/home'
    | '/admin/problem-options'
    | '/admin/profiles'
    | '/admin/records'
    | '/admin/settings'
    | '/admin/'
    | '/board/$slug'
    | '/board/'
    | '/board/$slug/$postNo'
    | '/board/$slug/new-general'
    | '/board/$slug/new-link'
    | '/board/$slug/new-problem'
    | '/board/$slug/new-project'
    | '/board/$slug/new-question'
    | '/board/$slug/new-record'
    | '/board/$slug/new-vote'
    | '/board/$slug/'
    | '/board/$slug/series/$series'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/guide'
    | '/home'
    | '/mypage'
    | '/readme'
    | '/search'
    | '/admin/calendar'
    | '/admin/categories'
    | '/admin/criteria'
    | '/admin/home'
    | '/admin/problem-options'
    | '/admin/profiles'
    | '/admin/records'
    | '/admin/settings'
    | '/admin'
    | '/board'
    | '/board/$slug/$postNo'
    | '/board/$slug/new-general'
    | '/board/$slug/new-link'
    | '/board/$slug/new-problem'
    | '/board/$slug/new-project'
    | '/board/$slug/new-question'
    | '/board/$slug/new-record'
    | '/board/$slug/new-vote'
    | '/board/$slug'
    | '/board/$slug/series/$series'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/admin'
    | '/_main/calendar'
    | '/_main/guide'
    | '/_main/home'
    | '/_main/mypage'
    | '/_main/readme'
    | '/_main/search'
    | '/admin/calendar'
    | '/admin/categories'
    | '/admin/criteria'
    | '/admin/home'
    | '/admin/problem-options'
    | '/admin/profiles'
    | '/admin/records'
    | '/admin/settings'
    | '/admin/'
    | '/_main/board/$slug'
    | '/_main/board/'
    | '/_main/board/$slug/$postNo'
    | '/_main/board/$slug/new-general'
    | '/_main/board/$slug/new-link'
    | '/_main/board/$slug/new-problem'
    | '/_main/board/$slug/new-project'
    | '/_main/board/$slug/new-question'
    | '/_main/board/$slug/new-record'
    | '/_main/board/$slug/new-vote'
    | '/_main/board/$slug/'
    | '/_main/board/$slug/series/$series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problem-options': {
      id: '/admin/problem-options'
      path: '/problem-options'
      fullPath: '/admin/problem-options'
      preLoaderRoute: typeof AdminProblemOptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/criteria': {
      id: '/admin/criteria'
      path: '/criteria'
      fullPath: '/admin/criteria'
      preLoaderRoute: typeof AdminCriteriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/readme': {
      id: '/_main/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof MainReadmeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mypage': {
      id: '/_main/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MainMypageRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/guide': {
      id: '/_main/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof MainGuideRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/calendar': {
      id: '/_main/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof MainCalendarRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/board/': {
      id: '/_main/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof MainBoardIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/board/$slug': {
      id: '/_main/board/$slug'
      path: '/board/$slug'
      fullPath: '/board/$slug'
      preLoaderRoute: typeof MainBoardSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/board/$slug/': {
      id: '/_main/board/$slug/'
      path: '/'
      fullPath: '/board/$slug/'
      preLoaderRoute: typeof MainBoardSlugIndexRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-vote': {
      id: '/_main/board/$slug/new-vote'
      path: '/new-vote'
      fullPath: '/board/$slug/new-vote'
      preLoaderRoute: typeof MainBoardSlugNewVoteRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-record': {
      id: '/_main/board/$slug/new-record'
      path: '/new-record'
      fullPath: '/board/$slug/new-record'
      preLoaderRoute: typeof MainBoardSlugNewRecordRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-question': {
      id: '/_main/board/$slug/new-question'
      path: '/new-question'
      fullPath: '/board/$slug/new-question'
      preLoaderRoute: typeof MainBoardSlugNewQuestionRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-project': {
      id: '/_main/board/$slug/new-project'
      path: '/new-project'
      fullPath: '/board/$slug/new-project'
      preLoaderRoute: typeof MainBoardSlugNewProjectRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-problem': {
      id: '/_main/board/$slug/new-problem'
      path: '/new-problem'
      fullPath: '/board/$slug/new-problem'
      preLoaderRoute: typeof MainBoardSlugNewProblemRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-link': {
      id: '/_main/board/$slug/new-link'
      path: '/new-link'
      fullPath: '/board/$slug/new-link'
      preLoaderRoute: typeof MainBoardSlugNewLinkRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/new-general': {
      id: '/_main/board/$slug/new-general'
      path: '/new-general'
      fullPath: '/board/$slug/new-general'
      preLoaderRoute: typeof MainBoardSlugNewGeneralRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/$postNo': {
      id: '/_main/board/$slug/$postNo'
      path: '/$postNo'
      fullPath: '/board/$slug/$postNo'
      preLoaderRoute: typeof MainBoardSlugPostNoRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
    '/_main/board/$slug/series/$series': {
      id: '/_main/board/$slug/series/$series'
      path: '/series/$series'
      fullPath: '/board/$slug/series/$series'
      preLoaderRoute: typeof MainBoardSlugSeriesSeriesRouteImport
      parentRoute: typeof MainBoardSlugRoute
    }
  }
}

interface MainBoardSlugRouteChildren {
  MainBoardSlugPostNoRoute: typeof MainBoardSlugPostNoRoute
  MainBoardSlugNewGeneralRoute: typeof MainBoardSlugNewGeneralRoute
  MainBoardSlugNewLinkRoute: typeof MainBoardSlugNewLinkRoute
  MainBoardSlugNewProblemRoute: typeof MainBoardSlugNewProblemRoute
  MainBoardSlugNewProjectRoute: typeof MainBoardSlugNewProjectRoute
  MainBoardSlugNewQuestionRoute: typeof MainBoardSlugNewQuestionRoute
  MainBoardSlugNewRecordRoute: typeof MainBoardSlugNewRecordRoute
  MainBoardSlugNewVoteRoute: typeof MainBoardSlugNewVoteRoute
  MainBoardSlugIndexRoute: typeof MainBoardSlugIndexRoute
  MainBoardSlugSeriesSeriesRoute: typeof MainBoardSlugSeriesSeriesRoute
}

const MainBoardSlugRouteChildren: MainBoardSlugRouteChildren = {
  MainBoardSlugPostNoRoute: MainBoardSlugPostNoRoute,
  MainBoardSlugNewGeneralRoute: MainBoardSlugNewGeneralRoute,
  MainBoardSlugNewLinkRoute: MainBoardSlugNewLinkRoute,
  MainBoardSlugNewProblemRoute: MainBoardSlugNewProblemRoute,
  MainBoardSlugNewProjectRoute: MainBoardSlugNewProjectRoute,
  MainBoardSlugNewQuestionRoute: MainBoardSlugNewQuestionRoute,
  MainBoardSlugNewRecordRoute: MainBoardSlugNewRecordRoute,
  MainBoardSlugNewVoteRoute: MainBoardSlugNewVoteRoute,
  MainBoardSlugIndexRoute: MainBoardSlugIndexRoute,
  MainBoardSlugSeriesSeriesRoute: MainBoardSlugSeriesSeriesRoute,
}

const MainBoardSlugRouteWithChildren = MainBoardSlugRoute._addFileChildren(
  MainBoardSlugRouteChildren,
)

interface MainRouteChildren {
  MainCalendarRoute: typeof MainCalendarRoute
  MainGuideRoute: typeof MainGuideRoute
  MainHomeRoute: typeof MainHomeRoute
  MainMypageRoute: typeof MainMypageRoute
  MainReadmeRoute: typeof MainReadmeRoute
  MainSearchRoute: typeof MainSearchRoute
  MainBoardSlugRoute: typeof MainBoardSlugRouteWithChildren
  MainBoardIndexRoute: typeof MainBoardIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCalendarRoute: MainCalendarRoute,
  MainGuideRoute: MainGuideRoute,
  MainHomeRoute: MainHomeRoute,
  MainMypageRoute: MainMypageRoute,
  MainReadmeRoute: MainReadmeRoute,
  MainSearchRoute: MainSearchRoute,
  MainBoardSlugRoute: MainBoardSlugRouteWithChildren,
  MainBoardIndexRoute: MainBoardIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCriteriaRoute: typeof AdminCriteriaRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminProblemOptionsRoute: typeof AdminProblemOptionsRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCriteriaRoute: AdminCriteriaRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminProblemOptionsRoute: AdminProblemOptionsRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
